// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Infrastructure.EntityFrameworkGateway;

namespace TodoList.Infrastructure.EntityFrameworkGateway.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoList.Core.Entities.Item", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<bool>("Done");

                b.Property<string>("Title");

                b.HasKey("Id");

                b.ToTable("Item");

                b.HasData(
                    new
                    {
                        Id = new Guid("3b35f11e-7080-45e2-a152-afff5a325508"),
                            Done = true,
                            Title = "Fork the repository"
                    },
                    new
                    {
                        Id = new Guid("4b2f8170-c618-4cd6-91b9-25e3b2bfa53e"),
                            Done = false,
                            Title = "Clone the repository"
                    },
                    new
                    {
                        Id = new Guid("360644f3-abb5-410b-939d-78a6d07bd075"),
                            Done = false,
                            Title = "Create a branch"
                    },
                    new
                    {
                        Id = new Guid("f1f0adf8-255f-45ef-9528-d6c2c326240b"),
                            Done = false,
                            Title = "Make necessary changes and commit those changes"
                    },
                    new
                    {
                        Id = new Guid("72af359b-48d7-41cd-978b-38c82e1206d4"),
                            Done = false,
                            Title = "Push changes to GitHub"
                    },
                    new
                    {
                        Id = new Guid("e3da5d74-3fa4-4856-b0dd-d098e0f637ed"),
                            Done = false,
                            Title = "Submit your changes for review"
                    },
                    new
                    {
                        Id = new Guid("1798c99c-371e-497c-a529-a1e3667b9ece"),
                            Done = false,
                            Title = "Keeping your fork synced with this repository"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}